repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3

  - repo: local
    hooks:
    - id: run-tests
      name: Run Tests
      stages: [commit]
      entry: python3 -m unittest discover tests
      language: system
      pass_filenames: false
      always_run: true
      